### PR TITLE
Fix aarch64 flags

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
So, same problem for aarch64 and ppc64le:
```
+ which cppyy-generator
/usr/bin/which: no cppyy-generator in (/home/conda/feedstock_root/build_artifacts/cppyy-cling_1663343058073/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac:/home/conda/feedstock_root/build_artifacts/cppyy-cling_1663343058073/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin:/home/conda/feedstock_root/build_artifacts/cppyy-cling_1663343058073/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/conda/bin)
```

**Comment by saraedum** [comment]
So, this is really bizarre:
```
$ ls -l /home/conda/feedstock_root/build_artifacts/cppyy-cling_1663368062934/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin
-rwxrwxr-x 1 conda conda     236 Sep 17 01:35 cppyy-generator
$ which cppyy-generator
/usr/bin/which: no cppyy-generator in (/home/conda/feedstock_root/build_artifacts/cppyy-cling_1663368062934/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac:/home/conda/feedstock_root/build_artifacts/cppyy-cling_1663368062934/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin:/home/conda/feedstock_root/build_artifacts/cppyy-cling_1663368062934/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/conda/bin)
```

**Comment by saraedum** [comment]
@isuruf, any input would be greatly appreciated :)

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by saraedum** [comment]
@isuruf, I'm none the wiser from looking at the artifacts. Did you get anything out of it?

**Comment by saraedum** [comment]
@conda-forge-admin, rerender

**Comment by saraedum** [comment]
> So, this is really bizarre:
> 
> ```
> $ ls -l /home/conda/feedstock_root/build_artifacts/cppyy-cling_1663368062934/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin
> -rwxrwxr-x 1 conda conda     236 Sep 17 01:35 cppyy-generator
> $ which cppyy-generator
> /usr/bin/which: no cppyy-generator in (/home/conda/feedstock_root/build_artifacts/cppyy-cling_1663368062934/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac:/home/conda/feedstock_root/build_artifacts/cppyy-cling_1663368062934/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin:/home/conda/feedstock_root/build_artifacts/cppyy-cling_1663368062934/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/conda/bin)
> ```

@isuruf, still the same problem. No clue what's going on here. The binary is obivously in the `$PATH` but `which` does not see it.

**Comment by isuruf** [comment]
It depends on the path where the program is too

**Comment by isuruf** [comment]
`s/256/512/g` in which.c of the which-2.21.tar.gz sources and recompiling makes things work.

**Comment by saraedum** [comment]
> `s/256/512/g` in which.c of the which-2.21.tar.gz sources and recompiling makes things work.

lol, that's awesome :)

So, I'll just modify the checks.

**Pull request merged**
