### PR TITLE
Drop constraint on using old clang

### PR DESCRIPTION
**Pull request by saraedum**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
@wlav, should we just ignore this warning?

`/Users/runner/miniforge3/conda-bld/cppyy-cling_1700996283849/work/src/io/io/src/TGenCollectionStreamer.cxx:395:18: error: integer value 536870912 is outside the valid range of values [0, 63] for this enumeration type [-Wenum-constexpr-conversion]`

**Comment by wlav** [comment]
> @wlav, should we just ignore this warning?

I don't understand the error, as `EProperty` has explicit values set and these are well out of the `[0, 63]` range? The type of the variable over which the switch is set is `unsigned int`, so also bigger.

That said, yes, fine to ignore. I've always kept the I/O code thinking of one day supporting it (it can be used to pickle and C++ object, for example), but it's going away completely with the move to clang-repl. Might revive it in simplified form (w/o all the backwards compatibility to ancient formats, scheme evolution, etc.).

**Comment by saraedum** [comment]
Not an issue with the latest cppyy-cling anymore.

**Pull request closed without merging**
